-- Vendor
insert into `vendor` (`id`, `createTime`, `createUser`, `identification`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 17:13:42', 'Miguel', '1061', 'Andres', '2023-05-27 17:13:42', NULL);

-- Modality
insert into `modality` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:23:39', 'Miguel', 'Contratos que superan los 50 Millones de pesos', '123C', '+ 50 Millones', '2023-05-27 18:23:39', NULL);
insert into `modality` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:23:39', 'Sebastian', 'Contratos que superan los 100 SMMLV', '1M', 'Mayor a 100 SMMLV', '2023-05-27 18:23:39', NULL);
insert into `modality` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:23:39', 'Sebastian', 'Contratos que son inferiores o iguales a 100 SMMLV', '2M', 'Inferior o igual a 100 SMMLV', '2023-05-27 18:23:39', NULL);

-- ContractTyp
insert into `contracttype` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:26:17', 'Miguel', 'Contratos de prestación de servicios', '123P', 'Prestación de Servicios', '2023-05-27 18:26:17', NULL);
insert into `contracttype` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:26:17', 'Sebastian', 'Contratos de suministro', '123S', 'Suministro', '2023-05-27 18:26:17', NULL);
insert into `contracttype` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:26:17', 'Sebastian', 'Contratos de compraventa y suministro', '123C', 'Compraventa y suministro', '2023-05-27 18:26:17', NULL);
insert into `contracttype` (`id`, `createTime`, `createUser`, `description`, `externalCode`, `name`, `updateTime`, `updateUser`) VALUES (NULL, '2023-05-27 18:26:17', 'Sebastian', 'Contratos de obra', '123O', 'Obra', '2023-05-27 18:26:17', NULL);

-- ModalityContractType
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Miguel', '2023-05-27 18:27:30', NULL, 1, 1);
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Sebastian', '2023-05-27 18:27:30', NULL, 2, 2);
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Sebastian', '2023-05-27 18:27:30', NULL, 2, 3);
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Sebastian', '2023-05-27 18:27:30', NULL, 3, 2);
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Sebastian', '2023-05-27 18:27:30', NULL, 3, 4);
insert into `modalitycontracttype` (`id`, `createTime`, `createUser`, `updateTime`, `updateUser`, `modalityId`, `contractTypeId`) VALUES (NULL, '2023-05-27 18:27:30', 'Sebastian', '2023-05-27 18:27:30', NULL, 3, 1);

-- Contract
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2023-05-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.1', '2023-05-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2023-05-27 15:50:41', NULL, 1, 1);
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2023-06-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.2', '2023-05-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2023-06-27 15:50:41', NULL, 1, 1);
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2023-07-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.3', '2023-05-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2023-07-27 15:50:41', NULL, 1, 1);
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2024-05-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.4', '2023-01-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2024-05-27 15:50:41', NULL, 1, 1);
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2024-06-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.5', '2023-05-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2024-06-27 15:50:41', NULL, 1, 1);
insert into `contract` (`id`, `createTime`, `createUser`, `finalDate`, `initialDate`, `reference`, `signingDate`, `status`, `subject`, `updateTime`, `updateUser`, `vendorId`, `modalityContractTypeId`) VALUES (NULL, '2024-07-27 15:50:41', 'Miguel', '2024-05-01 15:48:41', '2023-05-30 15:48:41', 'xxx.yyy.zzz.6', '2023-05-27 15:48:41', 'ACTIVO', 'Gastar el dinero de la U', '2024-07-27 15:50:41', NULL, 1, 1);

-- ContractualDocumentType
insert into `contractualdocumenttype` (`id`, `CreateTime`, `CreateUser`, `Description`, `Name`, `UpdateTime`, `UpdateUser`) VALUES (NULL, '2023-06-04 11:53:00', 'Sebastian', 'Etapa del contrato precontractual', 'PRECONTRACTUAL', NULL, NULL);
insert into `contractualdocumenttype` (`id`, `CreateTime`, `CreateUser`, `Description`, `Name`, `UpdateTime`, `UpdateUser`) VALUES (NULL, '2023-06-04 11:53:00', 'Sebastian', 'Etapa del contrato contractual', 'CONTRACTUAL', NULL, NULL);
insert into `contractualdocumenttype` (`id`, `CreateTime`, `CreateUser`, `Description`, `Name`, `UpdateTime`, `UpdateUser`) VALUES (NULL, '2023-06-04 11:53:00', 'Sebastian', 'Etapa del contrato postcontractual', 'POSTCONTRACTUAL', NULL, NULL);
-- Contrato de Prestacion de servicio inferior o igual a 100 SMLMV
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud de contratación PA-GA-5-FOR-38', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificación de la División de Gestión del Talento Humano (Aplica para funcionamiento)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto del convenio o proyecto (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Vigencia de Contratos, Convenios, Proyectos PA-GA-5-FOR-2 (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Para cuantía menor o igual a 50 SMMLV: Mínimo una (1) cotización', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Para cuantía mayor a 50 y hasta 100 SMMLV: Mínimo tres (3) cotizaciones.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Disponibilidad Presupuestal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Invitación a cotizar a mínimo 3 proveedores (Aplica para contratos mayores a 50 y hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de recepción de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de apertura de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación inicial de requisitos habilitantes (jurídico, financiero y técnico). Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación definitivo. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Resolución de Adjudicación o de declaración de desierta (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo carta de presentación de la oferta. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de existencias y Representación Legal expedida por la cámara de comercio para persona jurídica.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de matrícula mercantil (Persona Natural si aplica).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Hoja de vida SIGEP (soportes de estudio y experiencia).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documento de identidad persona natural o del representante legal.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Matrícula profesional (Cuando aplique).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado médico previo ocupacional.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fotocopia del RUT (Registro Único Tributario).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificación bancaria.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Soporte de afiliación al Sistema de Seguridad Social.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Fiscales.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Judiciales.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Disciplinarios.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Medidas correctivas.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Matriz de Riesgo.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Experiencia especifica del proponente (Aplica para contratos mayores de 50 hasta 100 SMLMV).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otros anexos de la oferta.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Estados Financieros  (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fichas técnicas, permisos, autorizaciones, personal, capacidad operativa y demás requisitos de la invitación a cotizar. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Propuesta económica', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '6');

insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Contrato de prestación de servicios', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro de disponibilidad presupuestal-RDP', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de estampillas Universidad del Cauca 180 años (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Garantía Única - Póliza de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación de garantía de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Oficio de designación de Supervisión', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de Inicio Formato: Código: PA.GA-5-FOR -16', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificados de pago PA-GA-FOR-24', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe de actividades', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Planillas de aportes a seguridad social (persona Natural), certificado del representante legal o del revisor fiscal (persona jurídica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobantes de egreso', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Formato evaluación proveedor', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud otrosi', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Justificación de conveniencia y oportunidad (otrosí)', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'CDP Otrosí (cuando aplique)', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otrosí', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'RDP Otrosí (cuando aplique)', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento (cuando aplique)', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento (cuando aplique)', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de suspensión y anexos', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de reinicio y anexos', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '6');
--Pos-contractual
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de liquidación Formato: Código: PA.GA-5-FOR -36', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '6');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobante de egreso final', b'0', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '6');

-- Contracto de Suministro inferior o igual a 100 SMLMV

insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud de contratación directa PA-GA-5-FOR-38', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Formato Solicitud de elementos PA-GA-5.4.5-FOR-4 (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Viabilidad técnica. Formato PA.GA-5-FOR-40 (para equipos)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto del convenio o proyecto (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Vigencia de Contratos, Convenios, Proyectos PA-GA-5-FOR-2 (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Una (1) cotización (especificación de los elementos y/o servicios discriminando el valor del IVA y el valor total debidamente suscrita) (Aplica para contratos de suministro de 0 hasta 50 SMLMV )', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Mínimo tres (3) cotizaciones que incluyan especificación de los elementos y/o servicios discriminando el valor del IVA y el valor total debidamente suscrita) (Aplica para contratos de suministro mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Disponibilidad Presupuestal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Invitación a cotizar a mínimo 3 proveedores (Aplica para contratos mayores a 50 y hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de recepción de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de apertura de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación inicial de requisitos habilitantes (jurídico, financiero y técnico). Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación definitivo. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Resolución de Adjudicación o de declaración de desierta (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otros anexos de la oferta', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo carta de presentación de la oferta. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de existencias y Representación Legal expedida por la cámara de comercio para persona jurídica.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de matrícula mercantil', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documento de identidad persona natural o del representante legal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fotocopia del RUT (Registro Único Tributario)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificación bancaria', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Soporte de cumplimiento al Sistema de Seguridad Social', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Fiscales', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Judiciales', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Disciplinarios', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Medidas correctivas', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Matriz de Riesgo', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Experiencia especifica del proponente (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otros anexos de la oferta', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Estados Financieros (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fichas técnicas, permisos, autorizaciones, personal, capacidad operativa y demás requisitos de la invitación a cotizar. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Propuesta económica', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '4');

insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Contrato de suministro', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro de disponibilidad presupuestal-RDP', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de estampillas Universidad del Cauca 180 años (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Garantía Única - Póliza de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación de garantía de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Oficio de designación de Supervisión', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de Inicio Formato: Código: PA.GA-5-FOR -16', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documentos de anticipo (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificados de pago PA-GA-FOR-24', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de recibo a satisfacción (PA-GA-5-FOR-22) para bienes o informe de actividades realizadas para servicios.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social Persona natural: Presentar planilla de pago con sus respectivos comprobantes.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social persona jurídica: presentar una certificación (expedida por el Revisor Fiscal o Representante Legal, en la que se indique que se encuentran al día en el pago de los aportes de sus empleados a los sistemas de salud, riesgos laborales, pensiones y parafiscales).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobantes de egreso', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Formato evaluación proveedor', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Justificación de conveniencia y oportunidad (otrosí)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'CDP Otrosí (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otrosí', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'RDP Otrosí (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'SUSPENSIÓN-REINICIO', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de suspensión y anexos', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de reinicio y anexos', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '4');

insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de liquidación Formato PA-GA-5-FOR-36', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '4');
insert into `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobante de egreso final', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '4');

-- Chequeo para Contrato de Obra de Inferior o Igual a 100 SMLMV

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud de contratación PA-GA-5-FOR-38', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Diseños de obra (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto del convenio o proyecto (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Vigencia de Contratos, Convenios, Proyectos PA-GA-5-FOR-2 (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Una (1) cotización (especificación de las obras discriminando el valor del AUI, debidamente suscrita) (Aplica para contratos de OBRA de 0 hasta 50 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Mínimo tres (3) cotizaciones que incluyan especificaciones técnicas de las obras discriminando el valor del AUI,debidamente suscritas) (Aplica para contratos de obra mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto de obra (Incluye AUI Administración Utilidad e Imprevisto, e IVA)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Análisis de precios Unitarios APU', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Viabilidad técnica de obra PA-GA-5-FOR-41', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Disponibilidad Presupuestal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Invitación a cotizar a mínimo 3 proveedores (Aplica para contratos mayores a 50 y hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de recepción de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de apertura de propuestas (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación inicial de requisitos habilitantes (jurídico, financiero y técnico). Aplica para contratos mayores de 50 hasta 100 SMLMV', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe evaluación definitivo. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Resolución de Adjudicación o de declaración de desierta (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo carta de presentación de la oferta. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de existencias y Representación Legal expedida por la cámara de comercio para persona jurídica.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de matrícula mercantil', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documento de identidad persona natural o del representante legal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fotocopia del RUT (Registro Único Tributario)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificación bancaria', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Soporte de cumplimiento al Sistema de Seguridad Social', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Fiscales', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Judiciales', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Antecedentes Disciplinarios', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Medidas correctivas', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Matriz de Riesgo', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Experiencia especifica del proponente (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otros anexos de la oferta', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro único de Proponentes (RUP)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Fichas técnicas, permisos, autorizaciones, personal, capacidad operativa y demás requisitos de la invitación a cotizar. (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Propuesta económica', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '5');

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Contrato de obra', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro de disponibilidad presupuestal-RDP', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de estampillas Universidad del Cauca 180 años (Aplica para contratos mayores de 50 hasta 100 SMLMV)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Garantía Única - Póliza de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación de garantía de cumplimiento (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Oficio de designación de Supervisión', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de Inicio Formato: Código: PA.GA-5-FOR -16', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documentos de anticipo (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificados de pago PA-GA-FOR-24', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de recibo a satisfacción para bienes (PA-GA-5-FOR-22) o informe de actividades realizadas para servicios', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social Persona natural: Presentar planilla de pago con sus respectivos comprobantes', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social persona jurídica: presentar una certificación (expedida por el Revisor Fiscal o Representante Legal, en la que se indique que se encuentran al día en el pago de los aportes de sus empleados a los sistemas de salud, riesgos laborales, pensiones y parafiscales)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobantes de egreso', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Formato evaluación proveedor', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud otrosí', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Justificación de conveniencia y oportunidad (otrosí)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'CDP Otrosí (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Otrosí', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'RDP Otrosí (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento (cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de suspensión y anexos', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Actas de reinicio y anexos', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Anexo ampliación póliza de cumplimiento', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación ampliación póliza de cumplimiento', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '5');

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de liquidación formato PA-GA-5-FOR-36', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '5');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobante de egreso final', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '5');

--  Contrato de Suministro y Compraventa mayores a 100 SMLMV

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud de Disponibilidad presupuestal (indicar con cargo a qué presupuesto, discriminando si es de funcionamiento o de inversión)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Justificación de Conveniencia y Oportunidad (Describir claramente la necesidad satisfacer. Explicar qué se pretende conseguir, cuál sería el resultado final de satisfacer la necesidad, hacer referencia de la importancia del contrato en el tiempo).', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto del convenio o proyecto (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Vigencia de Contratos, Convenios, Proyectos PA-GA-5-FOR-2 (solo para contratos enmarcados en proyectos o convenios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informe de estudios previos: objeto del contrato, valor del presupuesto oficial, Aval presupuestal del director del proyecto o convenio (solo para contratos enmarcados en proyectos o convenios), plazo, forma de pago, anticipo justificado (compraventa no aplica) o pago anticipado, obligaciones del contratista, lugar de ejecución del contrato, Clasificación UNSPSC, Modalidad de selección (en caso de contratación directa por excepción a la oferta publica se debe justificar de manera detallada),  clase de contrato a celebrar (compraventa o suministro), versión del plan anual de adquisiciones, nombre del supervisor sugerido, nombre y firma de la persona que elabora los estudios previos.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Formato Solicitud de elementos PA-GA-5.4.5-FOR-4', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Viabilidad técnica para adquisición de equipos Formato PA.GA-5-FOR-40 (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Estudio de Mercado (Incluir Cotizaciones y el informe del método utilizado para obtener los precios)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Presupuesto detallado', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Disponibilidad Presupuestal', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Viabilidad Administrativa', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Respuesta a observaciones al proyecto de Pliego de condiciones. (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Resolución de apertura', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Pliego de condiciones definitivo y anexos', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de recepción de ofertas', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de apertura de ofertas', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informes de evaluación final (Jurídico, Técnico y financiero)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de audiencia de adjudicación', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Resolución de Adjudicación o de declaración de desierta', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Oferta Ganadora', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '1', '3');

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Contrato de suministro o compraventa', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro de disponibilidad presupuestal-RDP', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', '(Póliza - suscrita por el contratista)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación de garantías', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Oficio de designación supervisor', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Estampilla Universidad del Cauca 180 años (APLICA PARA SUMINISTROS)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de Inicio Formato: Código: PA.GA-5-FOR -16', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Documentos de anticipo (Cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Solicitud y justificación de OTROSI', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de Disponibilidad presupuestal adicional (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'OTROSÍ', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Registro presupuestal adicional (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Póliza ampliada o modificada (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'aprobación de ampliación o modificación de garantía por OTROSI (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de suspensión Código PA-GA-5-FOR 3 (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`,`Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de reinicio Código PA-GA-5-FOR 27 (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Póliza modificada por suspensión y reinicio', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Aprobación de ampliación o modificación de garantía por suspensión y reinicio (si aplica)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Certificado de pago Formato: Código: PA.GA-5-FOR – 24', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Informes de seguimiento por la supervisión PA-GA-5-FOR-46, con corte al periodo facturado.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social persona natural: Presentar una certificación, en la que declare bajo la gravedad de juramento que ha cumplido con el pago de los aportes a los sistemas de Salud, Riesgos Laborales y Pensiones, planillas y comprobantes de pago.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Seguridad social persona jurídica: presentar una certificación (expedida por el Revisor Fiscal o representante legal, de conformidad con la ley), en la que se indique que se encuentran al día en el pago de los aportes de sus empleados a los sistemas de salud, riesgos laborales, pensiones y parafiscales, planillas y comprobantes de pago.', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de ingreso al área de adquisiciones e inventarios (solo aplica para bienes devolutivos)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Factura solo para contratistas pertenecientes al régimen común', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de recibo a satisfacción para cada pago (Aplica para compraventa)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobante de egreso para cada pago y desembolso de anticipo', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '2', '3');

INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Acta de liquidación formato PA-GA-5-FOR-36 (Aplica para suministros) (Para compraventa cuando aplique)', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Evaluación de proveedores formato PA-GA-5-FOR-39', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '3');
INSERT INTO `contractualdocument` (`id`, `CreateTime`, `CreateUser`, `Description`, `isRequired`, `Ordering`, `Subdirectory`, `UpdateTime`, `UpdateUser`, `contractualDocumentType`, `modalityContractType`) VALUES (NULL, '2023-06-05 05:11:15', 'Dacoes', 'Comprobante de egreso de pago final', b'1', '0', 'TODO', '2023-06-05 05:11:15', NULL, '3', '3');